language: node_js

node_js:
    - 15
    - 14
    - 12
    - 10

before_script:
    - grunt install_dependencias
    
script: grunt test

jobs:
    include:
        - stage: "Test sobre el contenedor" 
          language: minimal
          services: docker
          before_script: docker pull danielruizmed/pandemium
          script: docker run -t -v `pwd`:/test danielruizmed/pandemium


notifications:
    slack:
        on_success: never
        on_failure: never