include:
        - language: node_js
        node_js:
            - 15
            - 14
            - 12
            - 10
        before_script:
            - npm install -g grunt-cli
        script: grunt test

        - language: minimal
        services: docker
        before_script: docker pull danielruizmed/pandemium
        script: docker run -t -v `pwd`:/test danielruizmed/pandemium